= Constraints

Constraints provide a way of specifying and enforcing conditions at a
column level in a table schema definition and enforcing them at write time.

== CREATE CONSTRAINT

Constraints can be created within the column definition, or as part
of the table properties.

The main syntax to define a constraint is as follows:

[source,bnf]
----
CREATE TABLE ks.tb (
	name text,
	i int CHECK (condition) (AND (condition))*
	...,

);
----

As shown in this syntax, more than one constraint can be defined for a given column using the AND keyword.

== ALTER CONSTRAINT

Altering a constraint is done by following the alter column CQL syntax:
[source,bnf]
----
ALTER TABLE [IF EXISTS] <table> ALTER [IF EXISTS] <column> CHECK <condition>;
----

== DROP CONSTRAINT
And DROP can be used to drop constraints for a column as well.
[source,bnf]
----
ALTER TABLE [IF EXISTS] <table> ALTER [IF EXISTS] <column> DROP CHECK;
----

== AVAILABLE CONSTRAINTS

=== SCALAR CONSTRAINT

Defines a comparator against a numeric type. It support all numeric types supported in Cassandra, with all the regular
comparators.

For example, we can define constraints that ensure that i is bigger or equal than 100 but smaller than 1000.

[source,bnf]
----
CREATE TABLE ks.tb (
	name text,
	i int CHECK i < 1000 AND i > 100
	...,
);
----

Altering that constraint can be done with:

----
ALTER TABLE ks.tb ALTER i CHECK i >= 500;
----

Finally, the constraint can be removed:

----
ALTER TABLE ks.tb ALTER i DROP CHECK;
----

This constraint also works for `time`, `date` and `timestamp` types. For example, a user
can express constraints like this:

----
CREATE TABLE ks.tb
	name text,
	dob date CHECK dob > '1900-01-01'
    ...
)
----

Hence, we can enforce that date of birth is later than January 1st, 1900.

----
INSERT INTO ks.tb (name, dob) VALUES ( 'Joe Doe', '1899-08-06');
... [Invalid query] message="Column value does not satisfy value constraint for column 'dob'. It should be dob > '1900-01-01'"
-- this passes as it is > January 1st, 1900
INSERT INTO ks.tb (name, dob) VALUES ( 'Joe Doe', '1976-12-06');
----

A user can also use ranges on time-related columns with `>` and `<` operators, e.g.

----
CREATE TABLE ks.tb
	name text,
	afternoon time CHECK afternoon >= '12:00:00' AND afternoon <= '23:59:59';
    ...
)
----

=== LENGTH CONSTRAINT

Defines a condition that checks the length of text or binary type.

For example, we can create a constraint that checks that name can't be longer than 256 characters:

----
CREATE TABLE ks.tb (
	name text CHECK LENGTH(name) < 256
	...,
);
----

Altering that constraint can be done with:

----
ALTER TABLE ks.tb ALTER name LENGTH(name) < 512;
----

Finally, the constraint can be removed:

----
ALTER TABLE ks.tb ALTER name DROP CHECK;
----

=== OCTET_LENGTH CONSTRAINT

Defines a condition that checks the size in bytes of text or binary type.

For example, we can create a constraint that checks that name can't be bigger than 256 characters:

----
CREATE TABLE ks.tb (
	name text CHECK OCTET_LENGTH(name) < 2
	...,
);
----

Inserting a valid row:
----
INSERT INTO ks.tb (name) VALUES ("f")
----

Inserting an invalid row:
----
INSERT INTO ks.tb (name) VALUES ("fooooooo")

ERROR: Column value does not satisfy value constraint for column 'name'. It has a length of 8 and
and it should be should be < 2
----

=== NOT_NULL constraint

Defines a constraint that checks if a column is not null in every modification statement.

For example, let's have this table:

----
CREATE TABLE ks.tb (
    id int,
    cl int,
    col1 int CHECK NOT_NULL(col1),
    col2 int CHECK NOT_NULL(col2),
    PRIMARY KEY (id, cl)
);
----

then this statement would fail:

----
INSERT INTO ks.tb (id, cl, col1) VALUES (1, 2, 3);
... [Invalid query] message="Column 'col2' has to be specified as part of this query."
----

as well as this statement:

----
INSERT INTO ks.tb (id, cl, col1, col2) VALUES (1, 2, 3, null);
----

A column which has `NOT_NULL` constraint has to be specified in every modification statement.

The constraint can be removed:

----
ALTER TABLE ks.tb ALTER col1 DROP CHECK;
ALTER TABLE ks.tb ALTER col2 DROP CHECK;
----

We can not remove the value of a column where `NOT_NULL` constraint is present:

----
DELETE col2 FROM ks.tb WHERE id = 1 AND cl = 2;
... [Invalid query] message="Column 'col2' can not be set to null."
----

Additionally, `NOT_NULL` can not be specified on any column of a primary key,
being it a partition key or a clustering column.

=== JSON constraint

Defines a constraint which checks if a column contains a string which is a valid JSON.

`JSON` constraint can be used only for columns of `text`, `varchar` or `ascii` types.

----
CREATE TABLE ks.tb (
    id int primary key,
    val text CHECK JSON(val)
);

-- valid JSON string

INSERT INTO ks.tb (id, val) VALUES (1, '{"a": 5}');
INSERT INTO ks.tb (id, val) VALUES (1, '{}');

-- invalid JSON string

INSERT INTO ks.tb (id, val) VALUES (1, '{"a": 5');
INSERT INTO ks.tb (id, val) VALUES (1, 'abc');

... [Invalid query] message="Value for column 'val' violated JSON
constraint as it is not a valid JSON."

----

=== REGEXP constraint

Defines a constraint which checks text-like values againt a regular expression.

----
CREATE TABLE ks.tb (
    id int primary key,
    value CHECK REGEXP(value) = 'a.*b'
)
----

----
cassandra@cqlsh> INSERT INTO ks.tb (id , value ) VALUES ( 1, 'asdadasdabb');
cassandra@cqlsh> INSERT INTO ks.tb (id , value ) VALUES ( 1, 'aaaaa');
... [Invalid query] message="Value does not match regular expression 'a.*b'"
----

Negation can be also used:

----
ALTER TABLE ks.tb ALTER value CHECK REGEXP(value) != 'a.*b';
----

which would logically invert the condition:

----
cassandra@cqlsh> INSERT INTO ks.tb (id , value ) VALUES ( 1, 'asdadasdabb');
... [Invalid query] message="Value does match regular expression 'a.*b'"
cassandra@cqlsh> INSERT INTO ks.tb (id , value ) VALUES ( 1, 'aaaaa');
----