name: Comment on new Pull Request with checklist
on:
  pull_request:
    types: opened

jobs:
  checklist-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Add comment
        run: |
          sed "s/{{PR_NUMBER}}/$PRNUM/" .github/workflows/pr_checklist.md | gh pr comment $PRNUM --body-file -
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          PRNUM: ${{ github.event.pull_request.number }}
